### ISSUE TITLE
Interop Client dependency

### ISSUE THREAD

**Issue by rland93** [uci-uav-forge/uavf#39]
How do we install the interop client library so that it is accessible to a ROS node? https://github.com/auvsi-suas/interop/tree/master/client

They seem to be using Docker to set everything up, which is definitely a can of worms I would like not to open.

Steps to reproduce:

- enable ROS environment: `source /opt/ros/noetic/setup.sh`
- run `roscore`
- clone uavf into `catkin_ws/src`
- checkout ROS-dev
- run `catkin_make` in catkin_ws
- rosrun uavf interop.py

```
[ms:~/catkin_ws] $ rosrun uavf interop.py 
Traceback (most recent call last):
  File "/home/ms/catkin_ws/devel/lib/uavf/interop.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/ms/catkin_ws/src/uavf/interop.py", line 3, in <module>
    from interop_client import InteropClient
ModuleNotFoundError: No module named 'interop_client'
```
Was the interop code ever tested or run in a ROS environment?

**Comment by rland93** [comment]
I think we need to script this.

**Comment by rland93** [comment]
whoops, this isn't closed. Need to add to ROS documentation.

**Comment by rland93** [comment]
https://github.com/uci-uav-forge/uavf/commit/55a0f853674acd5beedda0a89a3f2a588bec8fe0 added documentation here
