### ISSUE TITLE
Some modules use relative, not absolute imports

### ISSUE THREAD

**Issue by rland93** [uci-uav-forge/uavf#48]
For example
```
Traceback (most recent call last):
  File "/home/ms/catkin_ws/devel/lib/uavf/planner", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/ms/catkin_ws/src/uavf/planner", line 5, in <module>
    from uavfpy.planner import mission
  File "/home/ms/.local/lib/python3.8/site-packages/uavfpy/planner/mission.py", line 2, in <module>
    import surface
ModuleNotFoundError: No module named 'surface'
```

This is because in `planner.py` we have

```python
import surface
```

instead of 
```python 
import .surface
```

which breaks imports when the module is imported in a script outside the source directory.

This is probably present in other areas of the codebase.

**Comment by rland93** [comment]
Resolved
