### ISSUE TITLE
Interop Client: Recieve and store mission from AUVSI

### ISSUE THREAD

**Issue by rland93** [uci-uav-forge/uavf#50]
On launch, the first thing we do is get a mission. So, we need to build the following functionality in interop:

- Get mission data as JSON from AUVSI server
- Start a service on the interop client (ideally, in its own thread).
- Unpack the JSON and store it into a single message `Mission.msg`. This message is kept in memory until:
- The interop client receives a request for a mission. At that point, it will pass the mission to the requestor.

---

You can compose messages, so rather than passing in FlyZoneArrays, ObjectArrays, and so on, just pack them into a single message when the mission data is received.

**Comment by rland93** [comment]
Great work. I was able to compile it, on running it I get 
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

I'm guessing because the interop server isn't running. 

Can we document how the interop server gets installed/launched?

And then test the service with the interop server running to make sure the mission is being fetched?
